language: node_js
node_js:
  - "8"
sudo: enabled

install:
- npm install
- npm install -g npx
- npm install -g allure-commandline
- apt-get install default-jre




jobs:
  include:
   - stage: unit tests
   script: echo running unit tests
   - stage: integration test
   script: echo running integration tests
   -stage: running end to end test
   script: npx ntaf run
   - stage: Generating reports
   script: allure generate allure-results --clean -o allure-report && allure open allure-report
